<?php 
// Include the header
include 'header.php';

// Check if we have enabled custom settings
$enable_custom_settings = get_option( DDTT_GO_PF.'error_enable' );

// Should we show the overwrite notice
$overwrite_notice = true;

// Listen for $_REQUEST to add Must-Use-Plugin; we will not be adding it by default
if ( isset( $_REQUEST ) && isset( $_REQUEST[ 'settings-updated' ] ) && $_REQUEST[ 'settings-updated' ] ) {
    if ( $enable_custom_settings ) {
        if ( DDTT_ERROR_REPORTING::add_remove_mu_plugin( 'add' ) ) {
            header( 'Refresh:0' );
            $overwrite_notice = false;
        }
    } else {
        DDTT_ERROR_REPORTING::add_remove_mu_plugin( 'remove' );
    }
}

// Check debug logging enabled
if ( WP_DEBUG ) {
    $debugging = 'ENABLED';
} else {
    $debugging = 'DISABLED';
}
?>
<style>
p.submit {
    display: inline-block;
}
#all-unchecked {
    display: none;
    margin-left: 10px;
    padding: 10px 12px;
    background: red;
    font-weight: bold;
    border-radius: 5px;
}
.false {
    color: #FF99CC;
}
#convert-error-code {
    width: 150px;
}
#error-code-constants {
    background-color: #2D2D2D;
    font-weight: bold;
    padding: 10px 12px;
    border-radius: 5px;
    visibility: hidden;
    display: inline-block;
    height: 18px;
}
#error-reporting-table .highlight-row td {
    background-color: yellow !important;
    color: black !important;
    font-weight: bold !important;
}
#error-reporting-table .highlight-row td .highlight-variable {
    color: black !important;
}
#error-reporting-table .highlight-row td a {
    color: #2271B1 !important;
}
#error-code-constants-notice {
    visibility: hidden;
    display: block;
    height: 18px;
    margin-top: 10px;
    font-style: italic;
}
#error-reporting-table td:nth-child(3),
#error-reporting-table td:nth-child(4) {
    text-align: center;
}
</style>

<form method="post" action="options.php">
    <?php settings_fields( DDTT_PF.'group_error' ); ?>
    <?php do_settings_sections( DDTT_PF.'group_error' ); ?>
    <table class="form-table">
        <?php 
        $allowed_html = ddtt_wp_kses_allowed_html();

        echo wp_kses( ddtt_options_tr( 'error_enable', 'Enable Custom Debug Levels', 'checkbox', 'Updating the error reporting level requires adding the settings via a Must-Use-Plugin so it loads before any regular plugin and before the theme is loaded.' ), $allowed_html );

        echo wp_kses( ddtt_options_tr( 'error_uninstall', 'Remove Must-Use-Plugin When Uninstalling Developer Debug Tools', 'checkbox', 'If enabled above, selecting this option will remove the Must-Use-Plugin upon uninstall. Keep this unchecked if you want to leave it.' ), $allowed_html );
        ?>

    </table>

    <br>
    <div class="full_width_container">

        <em>The "Actual" column has been added to verify what is actually set.</em>
        <br><br>

        <table id="error-reporting-table" class="admin-large-table">
            <tr>
                <th style="width: 50px;">Value</th>
                <th style="width: 180px;">Constant</th>
                <th style="width: 50px;">Enabled</th>
                <th style="width: 50px;">Actual</th>
                <th style="width: auto;">Description</th>
            </tr>
            <?php
            // Trigger error link
            $trigger = '<a href="https://www.php.net/manual/en/function.trigger-error.php" target="_blank">trigger_error()</a>';
            $set_error_handler = '<a href="https://www.php.net/manual/en/function.set-error-handler.php" target="_blank">set_error_handler()</a>';
            
            // All possible constants
            $data = [
                [ 1, 'E_ERROR', 'Fatal run-time errors. These indicate errors that can not be recovered from, such as a memory allocation problem. Execution of the script is halted.' ],
                [ 2, 'E_WARNING', 'Run-time warnings (non-fatal errors). Execution of the script is not halted.' ],
                [ 4, 'E_PARSE', 'Compile-time parse errors. Parse errors should only be generated by the parser.' ],
                [ 8, 'E_NOTICE', 'Run-time notices. Indicate that the script encountered something that could indicate an error, but could also happen in the normal course of running a script.' ],
                [ 16, 'E_CORE_ERROR', 'Fatal errors that occur during PHP\'s initial startup. This is like an <code class="hl">E_ERROR</code>, except it is generated by the core of PHP.' ],
                [ 32, 'E_CORE_WARNING', 'Warnings (non-fatal errors) that occur during PHP\'s initial startup. This is like an <code class="hl">E_WARNING</code>, except it is generated by the core of PHP.' ],
                [ 64, 'E_COMPILE_ERROR', 'Fatal compile-time errors. This is like an <code class="hl">E_ERROR</code>, except it is generated by the Zend Scripting Engine.' ],
                [ 128, 'E_COMPILE_WARNING', 'Compile-time warnings (non-fatal errors). This is like an <code class="hl">E_WARNING</code>, except it is generated by the Zend Scripting Engine.' ],	 
                [ 256, 'E_USER_ERROR', 'User-generated error message. This is like an <code class="hl">E_ERROR</code>, except it is generated in PHP code by using the PHP function '.$trigger.'.' ],
                [ 512, 'E_USER_WARNING', 'User-generated warning message. This is like an <code class="hl">E_WARNING</code>, except it is generated in PHP code by using the PHP function '.$trigger.'.' ],
                [ 1024, 'E_USER_NOTICE', 'User-generated notice message. This is like an <code class="hl">E_NOTICE</code>, except it is generated in PHP code by using the PHP function '.$trigger.'.' ],
                [ 2048, 'E_STRICT', 'Enable to have PHP suggest changes to your code which will ensure the best interoperability and forward compatibility of your code.' ],
                [ 4096, 'E_RECOVERABLE_ERROR', 'Catchable fatal error. It indicates that a probably dangerous error occurred, but did not leave the Engine in an unstable state. If the error is not caught by a user defined handle (see also '.$set_error_handler.'), the application aborts as it was an <code class="hl">E_ERROR</code>.' ],
                [ 8192, 'E_DEPRECATED', 'Run-time notices. Enable this to receive warnings about code that will not work in future versions.' ],
                [ 16384, 'E_USER_DEPRECATED', 'User-generated warning message. This is like an <code class="hl">E_DEPRECATED</code>, except it is generated in PHP code by using the PHP function '.$trigger.'.' ],
                [ 32767, 'E_ALL', 'All errors, warnings, and notices.' ]
            ];

            // Get our settings
            $enabled_constants = get_option( DDTT_GO_PF.'error_constants' );
            if ( $enabled_constants ) {
                $enabled_constants = filter_var_array( $enabled_constants, FILTER_SANITIZE_FULL_SPECIAL_CHARS );
                $enabled_constants = array_keys( $enabled_constants );
                $default = false;
            } else {
                $enabled_constants = [];
                $default = true;
            }

            // Error reporting exceptions
            $actual_constants = ddtt_get_error_reporting_constants();
            
            // Add E_ALL to actual for comparison only
            if ( in_array( 'E_ALL', $enabled_constants ) ) {
                $actual_constants[] = 'E_ALL';
            }

            // Notice
            if ( $enable_custom_settings && $overwrite_notice && $enabled_constants != $actual_constants ) {
                ?>
                <div class="notice notice-error is-dismissible">
                <p><?php _e( 'Uh-oh! It appears that another plugin, custom code, or your host is overwriting these error reporting values. Unfortunately this tool won\'t work for you. It was a nice thought, though. If you are on a Managed WordPress hosting plan, this is likely the problem. You might want to switch to a cPanel plan that gives you more flexibility.', 'dev-debug-tools' ); ?></p>
                </div>
                <?php
            }

            // Store the total values
            $total_enabled_values = 0;
            $total_actual_values = 0;

            // Allowed html
            $allowed_html = ddtt_wp_kses_allowed_html();

            // Iter the data
            foreach ( $data as $d ) {

                // Variables
                $value = $d[0];
                $variable = $d[1];
                $desc = $d[2];

                // Check actual
                if ( in_array( $variable, $actual_constants ) || ( $variable == 'E_ALL' && $total_actual_values == E_ALL ) ) {
                    $actual = true;
                    $total_actual_values += $value;
                } else {
                    $actual = false;
                }
                
                // Check if we enabled it
                if ( in_array( $variable, $enabled_constants ) || ( $variable == 'E_ALL' && $total_enabled_values == E_ALL ) ) {
                    $enabled = true;
                    $total_enabled_values += $value;
                } elseif ( $default ) {
                    $enabled = $actual;
                } else {
                    $enabled = false;
                }

                // Actual
                $display_actual = $actual ? '<span class="true">TRUE</span>' : '<span class="false">FALSE</span>';

                // Select field
                $input = '<input type="checkbox" id="error_constants_'.strtolower( $variable ).'" class="error_constants_checkboxes" name="'.DDTT_GO_PF.'error_constants['.$variable.']" value="1"'.checked( 1, $enabled, false ).'/>';

                // Add the row
                ?>
                <tr>
                    <td><?php echo absint( $value ); ?></td>
                    <td><span class="highlight-variable"><?php echo esc_html( $variable ); ?></span></td>
                    <td><?php echo wp_kses( $input, $allowed_html ); ?></td>
                    <td><?php echo wp_kses( $display_actual, $allowed_html ); ?></td>
                    <td><?php echo wp_kses( $desc, $allowed_html ); ?></td>
                </tr>
                <?php
            }

            // Remove E_ALL from totals
            if ( in_array( 'E_ALL', $enabled_constants ) ) {
                $total_enabled_values -= E_ALL;
                $total_actual_values -= E_ALL;
            }
            ?>
            <tr>
                <td colspan="2"></td>
                <td style="text-align: center;"><?php echo absint( $total_enabled_values ); ?></td>
                <td><?php echo absint( $total_actual_values ); ?></td>
                <td></td>
            </tr>
        </table>
    </div>

    <?php submit_button(); ?> <div id="all-unchecked">You cannot report on nothing. To disable reporting altogether, simply set <code class="hl">WP_DEBUG</code> to false on your <code class="hl">wp-config.php</code> file.</div>
</form>

<?php
$nonce = wp_create_nonce( DDTT_GO_PF.'check_error_code' );
?>

<br><br>
<table class="form-table">
    <tr>
        <th>Quickly Convert <code class="hl">error_reporting</code> Code to Constants</th>
        <td><input type="text" id="convert-error-code" data-nonce="<?php echo esc_attr( $nonce ); ?>" value=""></td>
    </tr>
</table>
<div id="error-code-constants"></div>
<div id="error-code-constants-notice">The codes are also highlighted in the table above.</div>